/**
 * This class is generated by jOOQ
 */
package com.shop.model;


import com.shop.model.tables.Profile;
import com.shop.model.tables.Role;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shop extends SchemaImpl {

	private static final long serialVersionUID = 1708535648;

	/**
	 * The reference instance of <code>shop</code>
	 */
	public static final Shop SHOP = new Shop();

	/**
	 * No further instances allowed
	 */
	private Shop() {
		super("shop");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Profile.PROFILE,
			Role.ROLE);
	}
}
