/**
 * This class is generated by jOOQ
 */
package com.shop.model;


import com.shop.model.tables.Profile;
import com.shop.model.tables.Role;


/**
 * Convenience access to all tables in shop
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table shop.profile
	 */
	public static final Profile PROFILE = com.shop.model.tables.Profile.PROFILE;

	/**
	 * The table shop.role
	 */
	public static final Role ROLE = com.shop.model.tables.Role.ROLE;
}
